#!/usr/bin/env bash
# usage: ./update 123.43 230.12

hot=$1
cold=$2
date=$3
date_str=`node -p "new Date('$3').toLocaleString('ru-RU', { month: 'long', day: 'numeric', hour: 'numeric', minute: 'numeric', second: 'numeric' })"` # e.g. 2020-3-17T16:55:57 -> 17 марта, 16:55:57
echo "update: hot: $hot; cold: $cold; date: $date"
sed "s/%hot%/$hot/" roscha-water-tpl.html | sed "s/%cold%/$cold/" | sed "s/%date%/$date_str/" > roscha-water.html
scp roscha-water.html root@invntrm.ru:/var/www/invntrm.ru/roscha/water.html

# check the https://invntrm.ru/roscha/water.html
